export const seedProducts: unknown = [
  {
    id: 'prod_oak_hardwood',
    slug: 'oak-solid-hardwood-plank',
    name: 'Oak Solid Hardwood Plank',
    description: 'Natural oak planks with a durable satin finish for living spaces and bedrooms.',
    category: 'flooring',
    price: { amount: 699, currency: 'USD' },
    priceUnit: 'square-foot',
    image: '/images/oak-solid-3.png',
    href: '/products/flooring/oak-hardwood',
    tags: ['oak', 'hardwood', 'wood flooring'],
    featured: true,
    popular: false,
  },
  {
    id: 'prod_waterproof_vinyl',
    slug: 'waterproof-vinyl-tile',
    name: 'Waterproof Vinyl Tile',
    description: 'Low-maintenance waterproof vinyl tile suited to kitchens, bathrooms, and basements.',
    category: 'flooring',
    price: { amount: 399, currency: 'USD' },
    priceUnit: 'square-foot',
    image: '/images/vinyl-tile-1.png',
    href: '/products/flooring/vinyl-tile',
    tags: ['vinyl', 'waterproof', 'tile'],
    featured: true,
    popular: false,
  },
  {
    id: 'prod_hexagon_mosaic',
    slug: 'hexagon-mosaic-tile',
    name: 'Hexagon Mosaic Tile',
    description: 'Classic hexagon mosaic tile for decorative floors, backsplashes, and shower walls.',
    category: 'flooring',
    price: { amount: 549, currency: 'USD' },
    priceUnit: 'square-foot',
    image: '/images/hexagon-tile-1.png',
    href: '/products/flooring/hexagon-tile',
    tags: ['ceramic', 'mosaic', 'hexagon', 'tile'],
    featured: true,
    popular: false,
  },
  {
    id: 'prod_interior_paint',
    slug: 'washable-interior-paint',
    name: 'Washable Interior Paint',
    description: 'Low-odor interior wall paint with a washable matte finish and excellent coverage.',
    category: 'paint-and-finishes',
    price: { amount: 4299, currency: 'USD' },
    priceUnit: 'each',
    image: '/images/interior-paints-1.png',
    href: '/products/painting/interior-paints',
    tags: ['paint', 'interior', 'matte', 'washable'],
    featured: false,
    popular: true,
  },
  {
    id: 'prod_paint_sprayer',
    slug: 'electric-paint-sprayer',
    name: 'Electric Paint Sprayer',
    description: 'Adjustable electric sprayer for smooth, even coverage on walls, fences, and furniture.',
    category: 'paint-and-finishes',
    price: { amount: 12999, currency: 'USD' },
    priceUnit: 'each',
    image: '/images/paint-sprayer-1.png',
    href: '/products/painting/paint-sprayer',
    tags: ['paint', 'sprayer', 'electric', 'finishing'],
    featured: false,
    popular: true,
  },
  {
    id: 'prod_painters_tape',
    slug: 'clean-edge-painters-tape',
    name: "Clean Edge Painter's Tape",
    description: 'Medium-adhesion painter tape that produces sharp lines and removes cleanly.',
    category: 'paint-and-finishes',
    price: { amount: 799, currency: 'USD' },
    priceUnit: 'each',
    image: '/images/tape-1.png',
    href: '/products/painting/painters-tape',
    tags: ['paint', 'tape', 'masking', 'decorating'],
    featured: false,
    popular: true,
  },
  {
    id: 'prod_step_ladder',
    slug: 'six-foot-step-ladder',
    name: '6-Foot Step Ladder',
    description: 'Lightweight folding step ladder with slip-resistant feet and a tool tray.',
    category: 'tools-and-hardware',
    price: { amount: 8999, currency: 'USD' },
    priceUnit: 'each',
    image: '/images/ladders-and-stools-1.png',
    href: '/products/tools/ladders',
    tags: ['ladder', 'step ladder', 'tools', 'folding'],
    featured: false,
    popular: true,
  },
];
